name: petroExploFlow
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - polars
  - geopandas
  - lasio
  - welly
  - scikit-learn
  - pytest
  - ruff
  - jupyter
  - notebook
  - pip
  - pip:
    - dlisio
    - striplog
    - segyio
